# CSC271H1 Lecture Exercises

## Week 2, Lecture 1

### 1. [NumPy 2D arrays] 

In the example above, we found the mean of all items in the 2D array. Now we want to find the mean of each row and of each column. To do so, explore the documentation for `mean`. We provide an abbreviated version of the relevant parts here:


```
mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>
)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.

[continued...]
```

#### Your task: use NumPy's mean function to calculate the means of each row and column of a 2D array.

In a 2D array, each sub-array is a row and a column is made up of all elements at the same index of the sub-arrays.
For example, for the array:

```
[[0, 1, 2, 3]
 [4, 5, 6, 7]
 [8, 9, 10, 11]]
```

The rows are `[0, 1, 2, 3]`, `[4, 5, 6, 7]`, and `[8, 9, 10, 11]`.

The columns are `[1, 4, 8]`, `[2, 5, 9]`, `[3, 6, 10]`, and `[4, 7, 11]`.

Do not use a loop.

In [6]:
import numpy as np

array = np.arange(12)       # creates an array with items 0 to 11 inclusive
grid = array.reshape(3, 4)  # produces a new view on the array data

print(f'Grid: \n{grid}')
print(f'Number of rows: {grid.shape[0]}')
print(f'Number of columns: {grid.shape[1]}\n')

# Task 1: print the mean of the elements in each column

print(f'Mean of each column: {grid.mean(axis=0)}')

# Task 2: print the mean of the elements in each row

print(f'Mean of each row: {grid.mean(axis=1)}')



Grid: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Number of rows: 3
Number of columns: 4

Mean of each column: [4. 5. 6. 7.]
Mean of each row: [1.5 5.5 9.5]


### 2. [Comparison and Masks] 

Complete the code fragments below according to their descriptions.

In [2]:
import numpy as np

inventory = np.array([3, 15, 0, 8, 22, 5, 1])

# Task 1. Create a Boolean mask for items that are out of stock (0).

out_of_stock = inventory == 0
print("Out of stock mask:", out_of_stock)

# Task 2. Create a Boolean mask for items that have low inventory (1 to 5, inclusive)

one_to_five = (inventory >= 1) & (inventory <= 5)
print("Low inventory mask:", one_to_five)

# Task 3. Calculate the mean quantity of items with an inventory amount of 6 and up.

inventory_six = inventory >= 6
mean_high_inventory = np.mean(inventory[inventory_six])
print("Mean quantity of items with inventory 6 and up:", mean_high_inventory)

Out of stock mask: [False False  True False False False False]
Low inventory mask: [ True False False False False  True  True]
Mean quantity of items with inventory 6 and up: 15.0
